/** D2R rune codes (r01–r33) and names for the Runes section */
export const RUNES: { code: string; name: string }[] = [
  { code: "r01", name: "El" },
  { code: "r02", name: "Eld" },
  { code: "r03", name: "Tir" },
  { code: "r04", name: "Nef" },
  { code: "r05", name: "Eth" },
  { code: "r06", name: "Ith" },
  { code: "r07", name: "Tal" },
  { code: "r08", name: "Ral" },
  { code: "r09", name: "Ort" },
  { code: "r10", name: "Thul" },
  { code: "r11", name: "Amn" },
  { code: "r12", name: "Sol" },
  { code: "r13", name: "Shael" },
  { code: "r14", name: "Dol" },
  { code: "r15", name: "Hel" },
  { code: "r16", name: "Io" },
  { code: "r17", name: "Lum" },
  { code: "r18", name: "Ko" },
  { code: "r19", name: "Fal" },
  { code: "r20", name: "Lem" },
  { code: "r21", name: "Pul" },
  { code: "r22", name: "Um" },
  { code: "r23", name: "Mal" },
  { code: "r24", name: "Ist" },
  { code: "r25", name: "Gul" },
  { code: "r26", name: "Vex" },
  { code: "r27", name: "Ohm" },
  { code: "r28", name: "Lo" },
  { code: "r29", name: "Sur" },
  { code: "r30", name: "Ber" },
  { code: "r31", name: "Jah" },
  { code: "r32", name: "Cham" },
  { code: "r33", name: "Zod" },
];
